# Generated by Django 4.0 on 2021-12-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название компании')),
                ('text', models.CharField(max_length=50, verbose_name='описание компании')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена акции')),
            ],
        ),
    ]
