# Generated by Django 4.0 on 2021-12-26 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_rename_name_stock_namestock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='text',
            new_name='description',
        ),
    ]
