# Generated by Django 3.2.9 on 2021-12-19 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RK2_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=30, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50, verbose_name='Название')),
                ('creationyear', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Год создания')),
            ],
        ),
        migrations.AddField(
            model_name='computer',
            name='os',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='RK2_app.operatingsystem'),
        ),
    ]
